import {chromium} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import path from 'node:path';
const root=process.env.BLUECHO_DEMO_ROOT||'E:/Hackathon/execution/phase1_engine_20260914/samples',out=process.env.BLUECHO_EVIDENCE||'E:/Hackathon/execution/dashboard_redesign_20260915/browser-wasm',url=process.env.BLUECHO_URL||'http://127.0.0.1:8010';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME||(process.platform==='win32'?'C:/Program Files/Google/Chrome/Application/chrome.exe':'/usr/bin/google-chrome'),headless:true});const context=await browser.newContext({viewport:{width:1536,height:1050},acceptDownloads:true});const page=await context.newPage();const errors=[],uploads=[],receipt={tests:[],runtime:'onnxruntime-web 1.30.0 WASM CPU'};page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message)});page.on('request',r=>{if(r.method()==='POST'||r.url().includes('/api/'))uploads.push(r.url())});
function pass(s){receipt.tests.push(s);console.log('PASS',s)}
try{
await page.goto(url);await page.locator('.specialist-card').first().waitFor();await page.screenshot({path:path.join(out,'01-browser-overview.png'),fullPage:true});
await page.getByLabel('Sonar source',{exact:true}).setInputFiles(path.join(root,'pipeline_positive.pbm'));await page.getByLabel('Confirm source modality').selectOption('SSS_LF');await page.getByLabel('Model route').selectOption('sss-pipeline-v3');await page.getByRole('button',{name:'Start inspection',exact:true}).click();await page.locator('.candidates h2').waitFor({timeout:180000});
const dlPromise=page.waitForEvent('download');await page.getByRole('button',{name:'JSON',exact:true}).click();const dl=await dlPromise;await dl.saveAs(path.join(out,'browser-pipeline.json'));const result=JSON.parse(await fs.readFile(path.join(out,'browser-pipeline.json'),'utf8'));assert.equal(result.detections.length,1);const d=result.detections[0];assert.ok(Math.abs(d.model_score-70.03985643386841)<.1);const expected=[998.8080101013184,.17437744140625,1096.0031433105469,500];assert.ok(Math.max(...d.box_xyxy_pixels.map((v,i)=>Math.abs(v-expected[i])))<.25);receipt.native_parity={browser_score:d.model_score,native_score:70.03985643386841,max_box_delta:Math.max(...d.box_xyxy_pixels.map((v,i)=>Math.abs(v-expected[i])))};pass('Real browser inference agrees with native pipeline example: score and box tolerances');assert.equal(d.coordinates,null);assert.equal(uploads.length,0);pass('No API requests or image uploads: inference and reporting run in browser');
await page.getByLabel('Review note',{exact:true}).fill('Browser runtime regression check');await page.getByRole('button',{name:'Save note',exact:true}).click();await page.getByRole('status').filter({hasText:'Review saved'}).waitFor();await page.reload();await page.locator('.candidates h2').waitFor();await page.getByText('Location, image context & provenance',{exact:true}).click();await page.getByText('Provenance, assumptions & history',{exact:true}).click();await page.getByText('Browser runtime regression check',{exact:false}).first().waitFor();pass('IndexedDB retains source, review revision and history across reload');
await page.getByLabel('Find a class').fill('not-a-pipeline');assert.equal(await page.locator('tbody tr').count(),0);await page.getByLabel('Find a class').fill('');assert.equal(await page.locator('tbody tr').count(),1);pass('Anomaly search filters real results');
for(const name of ['CSV','GEOJSON','Portable HTML + assets','Evidence ZIP']){const pending=page.waitForEvent('download');await page.getByRole('button',{name,exact:true}).click();const f=await pending;await f.saveAs(path.join(out,name.replaceAll(' ','-')+(name.includes('ZIP')||name.includes('HTML')?'.zip':'.txt')))}pass('CSV, GeoJSON, portable HTML and evidence ZIP download');
await page.screenshot({path:path.join(out,'02-browser-pipeline.png'),fullPage:true});
const metadata={schema_version:'1.0',source_sha256:result.source_sha256,image_width:2500,image_height:500,modality:'SSS_LF',mapping:'affine',crs:'EPSG:4326',transform:[.00001,0,-70,0,-.00001,20],input_provenance:'SYNTHETIC GEOMETRY SOFTWARE TEST; not field metadata'};
await page.getByText('Attach metadata to this saved result (no new inference)').click();await page.getByLabel('Geotag metadata').setInputFiles({name:'synthetic-geometry-test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(metadata))});await page.getByText('Metadata applied; no new inference.',{exact:false}).first().waitFor();await page.locator('[data-map-candidate]').first().waitFor();pass('Source-bound synthetic affine sidecar produces map location without rerunning inference');
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'03-browser-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));pass('Mobile workspace stays within 390px');
await page.getByRole('button',{name:'New inspection',exact:true}).click();await page.getByLabel('Sonar source',{exact:true}).setInputFiles(path.join(root,'pipeline_empty.pbm'));await page.getByLabel('Model route').selectOption('sss-pipeline-v3');await page.getByRole('button',{name:'Start inspection',exact:true}).click();await page.getByRole('heading',{name:'No automatic candidates',exact:true}).waitFor({timeout:180000});pass('Real negative image completes with zero candidates');
assert.deepEqual(errors,[]);receipt.status='PASS';
}catch(e){receipt.status='FAIL';receipt.failure=e.stack;await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e}finally{receipt.errors=errors;receipt.uploads=uploads;await fs.writeFile(path.join(out,'browser-runtime-receipt.json'),JSON.stringify(receipt,null,2));await browser.close()}
