import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const out=process.env.BLUECHO_EVIDENCE||'E:/Hackathon/execution/demo_20260915/browser';
await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
const errors=[],requests=[],receipt={checks:[]};
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
const pass=s=>{console.log('PASS',s);receipt.checks.push(s)};
async function download(name,file){const event=page.waitForEvent('download');await page.getByRole('button',{name,exact:true}).click();await(await event).saveAs(path.join(out,file));return fs.readFile(path.join(out,file));}
async function ready(){await page.waitForFunction(()=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Shuffle scene'));return b&&!b.disabled});await page.locator('[data-candidate]').first().waitFor();}
try{
 await page.goto(process.env.BLUECHO_URL||'http://127.0.0.1:8010');
 await page.getByRole('button',{name:'Try demo',exact:true}).click();await ready();
 assert.equal(await page.locator('[data-candidate]').count(),4);
 assert.ok(!requests.some(r=>/\.onnx|huggingface|\/api\/v1\/demo/.test(r)));
 pass('One click opens generated sonar and contacts without model downloads or a demo backend');
 const original=JSON.parse(await download('JSON','initial.json'));
 assert.equal(original.demo.kind,'synthetic_ui_demo');assert.equal(original.detections.length,4);
 await page.getByLabel('Review note',{exact:true}).fill('Demo review only');
 await page.getByRole('button',{name:'Retain candidate',exact:true}).click();
 await page.getByText('Review saved. This is not field verification.',{exact:true}).waitFor();
 const reviewed=JSON.parse(await download('JSON','reviewed.json'));
 assert.equal(reviewed.detections[0].review_state,'retained');
 await page.reload();await ready();
 assert.equal(JSON.parse(await download('JSON','restored.json')).detections[0].review_state,'retained');
 pass('Review actions persist across reload');
 await page.getByRole('button',{name:'Map',exact:true}).click();
 await page.getByText('DEMO MAP · FICTIONAL LOCATIONS',{exact:true}).waitFor();
 assert.equal(await page.locator('[data-map-candidate]').count(),4);
 await page.locator('[data-map-candidate]').last().click();
 await page.screenshot({path:path.join(out,'map.png'),fullPage:true});
 pass('Interactive map shows explicitly fictional locations');
 const csv=(await download('CSV','demo.csv')).toString();assert.match(csv,/demo/);assert.match(csv,/true/);
 const geo=JSON.parse(await download('GEOJSON','demo.geojson'));assert.ok(geo.features.every(f=>f.properties.demo));
 const reviews=JSON.parse(await download('Review candidates JSON','curation.json'));assert.ok(reviews.demo);assert.ok(reviews.candidates.every(c=>c.demo));
 assert.equal((await download('PDF brief','demo.pdf')).subarray(0,5).toString(),'%PDF-');
 await download('Evidence ZIP','demo.zip');
 pass('JSON, CSV, GeoJSON, curation JSON, PDF and evidence ZIP export successfully with demo provenance');
 await page.getByRole('button',{name:'Shuffle scene',exact:true}).click();await ready();
 const shuffled=JSON.parse(await download('JSON','shuffled.json'));
 assert.notEqual(shuffled.source_sha256,original.source_sha256);assert.notEqual(shuffled.demo.seed,original.demo.seed);
 await page.getByLabel('Demo scene',{exact:true}).selectOption('coverage');await ready();
 await page.getByRole('button',{name:'Quality',exact:true}).click();
 await page.getByText('simulated dark band',{exact:true}).waitFor();
 pass('Shuffle changes the scene and the coverage scenario exposes a generated quality band');
 await page.getByRole('button',{name:'Image',exact:true}).click();
 await page.screenshot({path:path.join(out,'workspace.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.screenshot({path:path.join(out,'workspace-mobile.png'),fullPage:true});
 await page.getByRole('button',{name:'Reports',exact:true}).click();
 await page.locator('.inspection-row').first().waitFor();
 await page.getByLabel('Search inspections').fill('Interrupted');assert.equal(await page.locator('.inspection-row').count(),1);
 await page.getByLabel('Search inspections').fill('');await page.getByLabel('Filter inspections').selectOption('uploads');assert.equal(await page.locator('.inspection-row .demo-label').count(),0);
 await page.getByLabel('Filter inspections').selectOption('demo');assert.equal(await page.locator('.inspection-row').count(),3);
 await page.screenshot({path:path.join(out,'reports-mobile.png'),fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:path.join(out,'reports.png'),fullPage:true});
 pass('Reports searches and filters demo history; workspace and reports fit mobile');
 await page.getByRole('button',{name:'Models',exact:true}).click();await page.locator('.model-profile').first().waitFor();
 await page.getByRole('button',{name:'Forward-looking',exact:true}).click();assert.ok(await page.locator('.model-profile').count()>=1);assert.ok((await page.locator('.model-sensor').allTextContents()).every(s=>s.includes('Forward-looking')));
 await page.getByRole('button',{name:'All sensors',exact:true}).click();
 await page.screenshot({path:path.join(out,'models.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,'models-mobile.png'),fullPage:true});
 await page.getByRole('button',{name:'Use model',exact:true}).first().click();await page.getByRole('heading',{name:'Start an inspection',exact:true}).waitFor();
 pass('Models filters by sonar type and routes to a new inspection');
 await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByLabel('Filter inspections').selectOption('demo');await page.getByRole('button',{name:'Clear demo history',exact:true}).click();await page.locator('.workspace-empty').waitFor();
 assert.equal(await page.locator('.inspection-row').count(),0);pass('Demo history clears independently');
 assert.deepEqual(errors,[]);receipt.status='PASS';
}catch(e){receipt.status='FAIL';receipt.failure=e.stack;await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e}
finally{receipt.errors=errors;await fs.writeFile(path.join(out,'receipt.json'),JSON.stringify(receipt,null,2));await browser.close()}
