import {chromium} from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const root=process.env.BLUECHO_SPECIALIST_SAMPLES||'E:/Hackathon/execution/coverage_expansion_20260915',out=process.env.BLUECHO_EVIDENCE||path.join(root,'browser-specialists'),url=process.env.BLUECHO_URL||'http://127.0.0.1:8010';await fs.mkdir(out,{recursive:true});
const b=await chromium.launch({headless:true,executablePath:process.env.CHROME||(process.platform==='win32'?'C:/Program Files/Google/Chrome/Application/chrome.exe':'/usr/bin/google-chrome')});const c=await b.newContext({viewport:{width:1536,height:1050},acceptDownloads:true});const p=await c.newPage(),errors=[],uploads=[],receipt={checks:[],runs:[]};p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.method()==='POST'||r.url().includes('/api/'))uploads.push(r.url())});const pass=s=>{console.log('PASS',s);receipt.checks.push(s)};
async function run(model,modality,file){await p.getByRole('button',{name:'New inspection',exact:true}).click();await p.getByLabel('Sonar source',{exact:true}).setInputFiles(file);await p.getByLabel('Confirm source modality').selectOption(modality);await p.getByLabel('Model route').selectOption(model);await p.getByRole('button',{name:'Start inspection',exact:true}).click();await p.locator('.candidates h2').waitFor({timeout:240000});const download=p.waitForEvent('download');await p.getByRole('button',{name:'JSON',exact:true}).click();const f=await download,name=model+'-'+receipt.runs.length+'.json';await f.saveAs(path.join(out,name));const result=JSON.parse(await fs.readFile(path.join(out,name),'utf8'));assert.equal(result.modality,modality);assert.ok(result.detections.every(d=>d.model_id===model));assert.ok(result.unvalidated_proposals.every(d=>d.model_id===model));receipt.runs.push({model,file:path.basename(file),detections:result.detections.map(d=>({class:d.class_name,score:d.model_score,box:d.box_xyxy_pixels})),proposals:result.unvalidated_proposals.map(d=>d.class_name)});return result}
try{await p.goto(url);await p.locator('.specialist-card').first().waitFor();assert.equal(await p.locator('.specialist-card').count(),4);await p.screenshot({path:path.join(out,'overview-desktop.png'),fullPage:true});pass('Four distinct model cards with explicit sensor selection');
 for(const [i,label] of ['propeller','shampoo-bottle','can'].entries()){const r=await run('fls11-debris','FLS_ARIS',path.join(root,`fls-sample-${i}.png`));assert.ok(r.detections.some(d=>d.class_name===label));assert.ok(r.detections.every(d=>d.coordinates===null));}pass('Real FLS browser inference finds propeller, shampoo-bottle and can without inventing locations');
 await p.getByRole('button',{name:'Focus view',exact:true}).click();await p.screenshot({path:path.join(out,'fls-focus.png'),fullPage:true});await p.getByRole('button',{name:'Exit focus',exact:true}).click();
 const ghost=await run('ghost-pot','SSS',process.env.BLUECHO_GHOST_SAMPLE||path.join(root,'sss-crop.png'));if(process.env.BLUECHO_GHOST_SAMPLE)assert.ok(ghost.detections.some(d=>d.class_name==='Crab-Pot'));pass('GhostVision ONNX executes in browser; labelled source-sample evaluation is reported separately');
 await run('sonarvision-sss','SSS',process.env.BLUECHO_WRECK_SAMPLE||'E:/Hackathon/execution/phase1_engine_20260914/samples/wreck_author_demo.jpg');pass('SonarVision ONNX executes with source class IDs and separately marked mine proposals');
 // Switching back to the original model verifies session release/reload across architectures.
 const pipe=await run('sss-pipeline-v3','SSS_LF',process.env.BLUECHO_PIPELINE_SAMPLE||'E:/Hackathon/execution/phase1_engine_20260914/samples/pipeline_positive.pbm');assert.equal(pipe.detections.length,1);assert.ok(Math.abs(pipe.detections[0].model_score-70.0398564)<.1);pass('Switching among models preserves original pipeline inference');
 await p.setViewportSize({width:390,height:844});await p.screenshot({path:path.join(out,'workspace-mobile.png'),fullPage:true});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.getByRole('button',{name:'New inspection',exact:true}).click();await p.screenshot({path:path.join(out,'overview-mobile.png'),fullPage:true});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));pass('Top navigation, gallery and inspection remain within mobile width');assert.deepEqual(errors,[]);assert.deepEqual(uploads,[]);pass('No page errors or sonar source uploads');receipt.status='PASS';
}catch(e){receipt.status='FAIL';receipt.failure=e.stack;await p.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e}finally{receipt.errors=errors;receipt.uploads=uploads;await fs.writeFile(path.join(out,'receipt.json'),JSON.stringify(receipt,null,2));await b.close()}
