/** Actual installed-backend E2E. Supply BLUECHO_DEMO_ROOT and BLUECHO_EVIDENCE. */
import{chromium}from'playwright';import fs from'node:fs/promises';import path from'node:path';import assert from'node:assert/strict';
const url=process.env.BLUECHO_URL||'http://127.0.0.1:8011',root=process.env.BLUECHO_DEMO_ROOT,out=process.env.BLUECHO_EVIDENCE;
if(!root||!out)throw Error('Set BLUECHO_DEMO_ROOT to Phase1 samples and BLUECHO_EVIDENCE to an empty evidence directory');await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1536,height:1000},deviceScaleFactor:2,acceptDownloads:true,recordVideo:{dir:out,size:{width:1280,height:832}}});const page=await context.newPage();const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!==url){external.push(u.origin);return route.abort()}return route.continue()});
const receipt={tests:[],jobs:{},external,errors};function pass(t){receipt.tests.push(t);console.log('PASS',t)}
async function request(p,data){const r=await context.request[data===undefined?'get':'post'](url+'/api/v1'+p,data===undefined?{}:{data});assert.equal(r.status(),200,await r.text());return r.json()}
async function waitResult(){await page.locator('.candidates h2').waitFor({timeout:90000});await page.locator('.sonar image').evaluate(async e=>{const image=new Image();image.src=e.getAttribute('href');await image.decode()});const id=await page.evaluate(()=>localStorage.getItem('bluecho-job'));const job=await request('/jobs/'+id);return{id,job,result:await request('/jobs/'+id+'/windows/0')}}
async function example(id,mode='run'){await page.getByRole('button',{name:'＋ New inspection',exact:true}).click();const names={noaa:'NOAA: review a false alert',empty:'Zero-candidate image',xtf:'Recording windows',wreck:'Experimental wreck',fls:'Supplemental FLS cylinder'};const card=page.locator('article').filter({has:page.getByRole('heading',{name:names[id],exact:true})});await card.getByRole('button',{name:mode==='run'?'Run example':'Open saved example',exact:true}).click();return waitResult()}
try{
 await page.goto(url);await page.getByRole('heading',{name:'Bring sonar evidence into focus.'}).waitFor();await page.screenshot({path:path.join(out,'01-new-inspection.png'),fullPage:true});
 await page.getByLabel('Sonar source',{exact:true}).setInputFiles(path.join(root,'pipeline_positive.pbm'));await page.getByLabel('Confirm source modality').selectOption('SSS_LF');await page.getByLabel('Model route').selectOption('sss-pipeline-v3');await page.getByRole('button',{name:'Start inspection →'}).click();const pipe=await waitResult();receipt.jobs.pipe=pipe;assert.equal(pipe.result.detections.length,1);assert.equal(pipe.job.saved_example,false);pass('Uploaded real pipeline image: actual CPU inference, one automatic box');
 const id=pipe.result.detections[0].candidate_id,box=pipe.result.detections[0].box_xyxy_pixels;const locator=page.locator(`[data-candidate="${id}"]`);await locator.click();assert.match(await page.locator(`[data-row="${id}"]`).getAttribute('class'),/selected/);
 async function alignment(){const measurement=await locator.evaluate((e,b)=>{const m=e.getScreenCTM();const a=new DOMPoint(b[0],b[1]).matrixTransform(m),z=new DOMPoint(b[2],b[3]).matrixTransform(m),r=e.getBoundingClientRect();return Math.max(Math.abs(r.x-a.x),Math.abs(r.y-a.y),Math.abs(r.width-(z.x-a.x)),Math.abs(r.height-(z.y-a.y)))},box);assert.ok(measurement<.1,`Box alignment error ${measurement}`)}
 await alignment();await page.getByRole('button',{name:'Zoom in',exact:true}).click();await alignment();await page.setViewportSize({width:1280,height:900});await alignment();await page.getByRole('button',{name:'Fit image',exact:true}).click();pass('SVG original-pixel box alignment at DPR 2, zoom and viewport resize; synchronized selection');
 await page.getByRole('button',{name:'Map',exact:true}).click();await page.getByRole('heading',{name:'No supported geographic geometry'}).waitFor();assert.equal(await page.locator('[data-map-candidate]').count(),0);pass('Missing coordinates: no fabricated map marker');await page.getByRole('button',{name:'Image',exact:true}).click();
 await page.getByLabel('Reviewer (optional)').fill('Automated browser test (not human ground truth)');await page.getByLabel('Review note',{exact:true}).fill('E2E persistence check');await page.getByRole('button',{name:'Save note',exact:true}).click();await page.getByRole('status').filter({hasText:'Review saved'}).waitFor();await page.reload();await waitResult();const reviewed=await request('/jobs/'+pipe.id+'/windows/0');assert.equal(reviewed.review_revision,1);assert.equal(reviewed.detections[0].review_history[0].note,'E2E persistence check');pass('Review note, identity and revision persist through browser refresh');
 await page.screenshot({path:path.join(out,'02-pipeline-review.png'),fullPage:true});
 const noaa=await example('noaa');receipt.jobs.noaa=noaa;assert.ok(noaa.result.detections[0].coordinates);await page.getByRole('button',{name:'Map',exact:true}).click();await page.locator('[data-map-candidate]').first().click();await page.screenshot({path:path.join(out,'03-noaa-vectors.png'),fullPage:true});pass('Real NOAA GeoTIFF live run: selectable positions and backend footprints, labels unconfirmed');
 await page.getByText('Correct label or box',{exact:true}).click();await page.getByLabel('Corrected label').fill('Uncertain mosaic boundary');await page.getByLabel('Original pixels: x1, y1, x2, y2').fill('400, 400, 900, 900');await page.getByRole('button',{name:'Save correction',exact:true}).click();await page.getByRole('status').filter({hasText:'Review saved'}).waitFor();const corrected=await request('/jobs/'+noaa.id+'/windows/0');const cd=corrected.detections[0];assert.deepEqual(cd.box_xyxy_pixels,[400,400,900,900]);assert.notDeepEqual(cd.coordinates,noaa.result.detections[0].coordinates);assert.ok(cd.metric_dimensions.width_m<510);assert.deepEqual(cd.original_prediction.box_xyxy_pixels,noaa.result.detections[0].box_xyxy_pixels);pass('Corrected box recomputes geography and footprint in Python; immutable original retained');
 for(const [name,format]of[['JSON','json'],['CSV','csv'],['GEOJSON','geojson'],['Portable HTML + assets','html'],['Evidence ZIP','zip']]){const promised=page.waitForEvent('download');await page.getByRole('button',{name,exact:true}).click();const dl=await promised;await dl.saveAs(path.join(out,'download-'+format+(format==='html'||format==='zip'?'.zip':'.'+format)));if(format==='json'){const r=JSON.parse(await fs.readFile(path.join(out,'download-json.json'),'utf8'));assert.equal(r.review_revision,corrected.review_revision);assert.deepEqual(r.detections[0].coordinates,cd.coordinates)}}pass('All five export controls download the current review revision');
 await page.getByRole('button',{name:'Quality',exact:true}).click();await page.getByLabel('Needs another scan: region x1, y1, x2, y2').fill('0, 0, 100, 100');await page.getByLabel('Reason',{exact:true}).fill('Automated UI test of human scan action');await page.getByRole('button',{name:'Save scan request'}).click();await page.getByRole('status').filter({hasText:'Human scan request recorded.'}).waitFor();pass('Explicit scan region and reason persist as human-action workflow, no autonomous plan');
 const empty=await example('empty');receipt.jobs.empty=empty;assert.equal(empty.result.detections.length,0);await page.getByRole('heading',{name:'No automatic candidates'}).waitFor();pass('Real zero-detection result remains usable');
 await page.getByRole('button',{name:'＋ New inspection',exact:true}).click();await page.getByLabel('Sonar source',{exact:true}).setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('not a sonar image')});await page.getByRole('alert').filter({hasText:/Cannot decode image|Invalid or unsupported image content/}).waitFor();pass('Invalid uploaded content produces a useful visible error');
 await page.getByRole('button',{name:'Dismiss error'}).click();
 await page.getByLabel('Sonar source',{exact:true}).setInputFiles(path.join(root,'aurora_real_32pings.xtf'));await page.getByLabel('Confirm source modality').selectOption('SSS');await page.getByLabel('Model route').selectOption('sss-wreck-experimental');await page.locator('.extent select').selectOption('1');await page.getByLabel('Starting ping ordinal').fill('4');await page.getByLabel('Ping limit (0 = all remaining)').fill('24');await page.getByLabel('Pings per window').fill('1');await page.getByRole('button',{name:'Start inspection →'}).click();const xtf=await waitResult();await page.getByRole('button',{name:'Cancel job',exact:true}).click();let cancelled;for(let i=0;i<200;i++){cancelled=await request('/jobs/'+xtf.id);if(cancelled.state==='cancelled')break;await page.waitForTimeout(100)}assert.equal(cancelled.state,'cancelled');assert.equal(cancelled.request.channel,1);assert.equal(cancelled.request.start_ping,4);assert.equal(cancelled.request.max_pings,24);assert.equal(cancelled.request.chunk_pings,1);assert.ok(cancelled.windows.length>=1&&cancelled.windows.length<24);receipt.jobs.xtf=cancelled;await page.screenshot({path:path.join(out,'05-cancelled-recording.png'),fullPage:true});pass('Browser XTF extent controls reach backend; cancel retains partial inferred windows');
 const saved=await example('wreck','saved');assert.ok(saved.job.saved_example);await page.getByText('SAVED EXAMPLE · no new inference',{exact:true}).waitFor();pass('Saved examples explicitly distinguished from live inference');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'04-mobile-review.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>document.activeElement!==document.body));pass('390px responsive review has no horizontal overflow; keyboard focus usable');
 pass('Bundled frontend and actual inference operate with external browser requests blocked');assert.deepEqual(external,[]);assert.deepEqual(errors.filter(e=>!e.includes('422 (Unprocessable Entity)')),[]);receipt.status='PASS';
}catch(e){receipt.status='FAIL';receipt.failure=e.stack;await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw e}finally{await fs.writeFile(path.join(out,'browser-receipt.json'),JSON.stringify(receipt,null,2));await context.close();await browser.close()}
