/** Real, source-bound browser inference. Images never leave this browser. */
import JSZip from 'jszip';
import proj4 from 'proj4';
proj4.defs('EPSG:26915','+proj=utm +zone=15 +datum=NAD83 +units=m +no_defs');
import {REAL_DEMO_SAMPLES,nextDemoScenario} from './demo-scene';
import {SPECIALISTS,predictSpecialist} from './specialist-inference';
type Obj=Record<string,any>;
export const browserMode=import.meta.env.VITE_BROWSER_ENGINE==='1';
const MODEL='https://huggingface.co/SharonMelhi/BluEcho-SSS-Pipeline/resolve/36055030359ec3c750c4446889c67fe10c5e7271/native.onnx';
const HASH='128d715c63b90af76dc43ca9cf4407ca76715194b20e1e2d6e502eb785e61bbc';
const THRESHOLD=.6818633675575256;
const urls=new Map<string,string>(),jobs=new Map<string,Obj>();
let sessionHash='';
let database:Promise<IDBDatabase>|undefined,session:Promise<any>|undefined,working=false;
const uid=()=>crypto.randomUUID().replaceAll('-','');
const sha=async(b:ArrayBuffer)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b)),x=>x.toString(16).padStart(2,'0')).join('');
const clone=(x:any)=>structuredClone(x);
function db(){return database??=new Promise((resolve,reject)=>{const r=indexedDB.open('bluecho-browser-v1',1);r.onupgradeneeded=()=>{for(const n of ['sources','jobs','models'])r.result.createObjectStore(n)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(Error('Browser storage is unavailable. Allow site storage or use the local app.'))})}
async function get(store:string,key:string):Promise<any>{const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(store).objectStore(store).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function put(store:string,key:string,value:any){const d=await db();await new Promise<void>((resolve,reject)=>{const t=d.transaction(store,'readwrite');t.objectStore(store).put(value,key);t.oncomplete=()=>resolve();t.onerror=()=>reject(Error('Browser storage is full. Export reports and clear site data to continue.'))})}
async function list(store:string):Promise<any[]>{const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
const canvas=(w:number,h:number)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c};
const blob=(c:HTMLCanvasElement)=>new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(Error('Could not encode image')),'image/png'));
function cacheURL(key:string,b:Blob){if(!urls.has(key))urls.set(key,URL.createObjectURL(b))}
export function evidenceURL(base:string,name:string){return browserMode||base.includes('/jobs/demo_')?(urls.get(base+'/evidence/'+name)||''):base+'/evidence/'+name}
async function decode(file:File){
 if(file.size>32*1024**2)throw Error('Browser images are limited to 32 MiB. Use the local app for larger inputs.');
 if(!/\.(png|jpe?g|bmp|pbm)$/i.test(file.name))throw Error('Browser inference accepts PNG, JPEG, BMP and PBM. Use the local BluEcho app for TIFF/GeoTIFF and raw XTF logs.');
 let c:HTMLCanvasElement;
 if(/\.pbm$/i.test(file.name)){
  const b=new Uint8Array(await file.arrayBuffer());let p=0;
  function word(){while(p<b.length){if(b[p]===35){while(p<b.length&&b[p]!==10)p++}else if(b[p]<=32)p++;else break}let s='';while(p<b.length&&b[p]>32&&b[p]!==35)s+=String.fromCharCode(b[p++]);return s}
  const magic=word(),w=Number(word()),h=Number(word());if(!['P1','P2','P3','P4','P5','P6'].includes(magic)||!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1||w*h>8_000_000)throw Error('Invalid or oversized PBM; maximum 8 million pixels.');
  c=canvas(w,h);const ctx=c.getContext('2d')!,im=ctx.createImageData(w,h);
  if(['P5','P6'].includes(magic)){const max=Number(word());if(max!==255)throw Error('Browser PGM/PPM requires 8-bit samples (maxval 255). Use the local app for other depths.');if(b[p]===13&&b[p+1]===10)p+=2;else p++;const channels=magic==='P6'?3:1;if(b.length-p<w*h*channels)throw Error('Truncated PGM/PPM');for(let i=0;i<w*h;i++){const offset=p+i*channels;im.data.set(channels===3?[b[offset],b[offset+1],b[offset+2],255]:[b[offset],b[offset],b[offset],255],i*4)}}
  else if(magic==='P4'){if(b[p]===13&&b[p+1]===10)p+=2;else p++;const row=Math.ceil(w/8);if(b.length-p<row*h)throw Error('Truncated PBM data');for(let y=0;y<h;y++)for(let x=0;x<w;x++){const v=b[p+y*row+(x>>3)]&(128>>(x%8))?0:255,i=(y*w+x)*4;im.data.set([v,v,v,255],i)}}
  else if(magic==='P1'){for(let i=0;i<w*h;i++){const n=word();if(n!=='0'&&n!=='1')throw Error('Invalid PBM pixel');const v=n==='1'?0:255;im.data.set([v,v,v,255],i*4)}}else{throw Error('Use binary P5/P6 for grayscale/color portable images')}ctx.putImageData(im,0,0);
 }else{let image:ImageBitmap;try{image=await createImageBitmap(file)}catch{throw Error('Invalid or unsupported image content')};if(image.width*image.height>8_000_000){image.close();throw Error('Browser analysis is limited to 8 million pixels. Use the local app for larger strips.')};c=canvas(image.width,image.height);c.getContext('2d')!.drawImage(image,0,0);image.close()}
 return {image:await blob(c),width:c.width,height:c.height};
}
const starts=(n:number)=>{if(n<=640)return[0];const a=[];for(let i=0;i<=n-640;i+=480)a.push(i);if(a[a.length-1]!==n-640)a.push(n-640);return a};
export function iou(a:number[],b:number[]){const inter=Math.max(0,Math.min(a[2],b[2])-Math.max(a[0],b[0]))*Math.max(0,Math.min(a[3],b[3])-Math.max(a[1],b[1]));const u=(a[2]-a[0])*(a[3]-a[1])+(b[2]-b[0])*(b[3]-b[1])-inter;return u>0?inter/u:0}
export function nms(boxes:Obj[],threshold:number,max=Infinity){const kept:Obj[]=[];for(const b of boxes.sort((a,b)=>b.score-a.score)){if(kept.every(k=>iou(b.box,k.box)<=threshold))kept.push(b);if(kept.length>=max)break}return kept}
async function loadModel(hash=HASH,url=MODEL){if(session&&sessionHash!==hash){const previous=await session;await previous.model.release();session=undefined}sessionHash=hash;if(!session)session=(async()=>{const ort=await import('onnxruntime-web/wasm');ort.env.wasm.numThreads=1;ort.env.wasm.wasmPaths='/ort/';let bytes=await get('models',hash);if(!bytes){const r=await fetch(url);if(!r.ok)throw Error('The model could not be downloaded from Hugging Face. Check your connection and retry.');bytes=await r.arrayBuffer()}if(await sha(bytes)!==hash)throw Error('Model checksum mismatch; the detector was not loaded.');await put('models',hash,bytes);return {ort,model:await ort.InferenceSession.create(bytes,{executionProviders:['wasm'],graphOptimizationLevel:'all'})}})().catch(e=>{session=undefined;throw e});return session}
function location(box:number[],metadata?:Obj){if(!metadata)return {coordinates:null,geographic_footprint:null,metric_dimensions:null,position_method:null,position_reason:'geographical_metadata_unavailable',uncertainty:{status:'unknown'}};
 const [a,b,c,d,e,f]=metadata.transform;const point=(x:number,y:number)=>{if(metadata.pixel_convention==='pixel_center'){x-=.5;y-=.5}let lon=a*x+b*y+c,lat=d*x+e*y+f;if(metadata.crs==='EPSG:26915'){[lon,lat]=proj4('EPSG:26915','EPSG:4326',[lon,lat])}else if(metadata.crs==='EPSG:3857'){lon=lon/6378137*180/Math.PI;lat=(2*Math.atan(Math.exp(lat/6378137))-Math.PI/2)*180/Math.PI}if(!Number.isFinite(lon)||!Number.isFinite(lat)||Math.abs(lon)>180||Math.abs(lat)>90)throw Error('Metadata maps the image outside valid geographic coordinates');return[lon,lat]};
 const [x,y,z,t]=box,coordinates=point((x+z)/2,(y+t)/2),foot=[point(x,y),point(z,y),point(z,t),point(x,t),point(x,y)];
 return {coordinates,geographic_footprint:foot,metric_dimensions:null,position_method:'supplied_raster_affine',position_reason:null,uncertainty:{status:'unknown'},crs:'EPSG:4326'};
}
function validateMetadata(m:Obj,s:Obj){if(m.schema_version!=='1.0'||m.source_sha256!==s.sha||m.image_width!==s.info.width||m.image_height!==s.info.height||!['SSS_LF','SSS','FLS_ARIS','FLS_UATD'].includes(m.modality))throw Error('Metadata must match the original file SHA256, dimensions and a supported sonar modality.');if(m.mapping!=='affine'||!['EPSG:4326','EPSG:3857','EPSG:26915'].includes(m.crs))throw Error('Browser geotagging supports affine JSON metadata in EPSG:4326, EPSG:3857 or EPSG:26915. Use the local app for ping-row metadata or other coordinate systems.');if(!Array.isArray(m.transform)||m.transform.length!==6||!m.transform.every(Number.isFinite)||Math.abs(m.transform[0]*m.transform[4]-m.transform[1]*m.transform[3])<1e-18)throw Error('Invalid affine transform');if(m.pixel_convention&&!['pixel_edge','pixel_center'].includes(m.pixel_convention))throw Error('Unsupported pixel convention');location([0,0,s.info.width,s.info.height],m)}
async function hydrate(j:Obj){if(!j.result)return;const s=await get('sources',j.request.source_id),base='/api/v1/jobs/'+j.id+'/windows/0/evidence/';cacheURL(base+'original.png',s.image);cacheURL(base+'quality.png',j.qualityImage||s.image);for(const [n,b]of Object.entries(j.contexts||{}))cacheURL(base+n,b as Blob)}
function publicJob(j:Obj){const {result,contexts,qualityImage,...rest}=j;return clone(rest)}
async function save(j:Obj){jobs.set(j.id,j);await put('jobs',j.id,j)}
function quality(image:HTMLCanvasElement){const ctx=image.getContext('2d')!,data=ctx.getImageData(0,0,image.width,image.height).data,regions:Obj[]=[];let begin=-1;for(let y=0;y<=image.height;y++){let dark=false;if(y<image.height){let sum=0,max=0,n=0;for(let x=0;x<image.width;x+=4){const i=(y*image.width+x)*4,v=(data[i]+data[i+1]+data[i+2])/3;sum+=v;max=Math.max(max,v);n++}dark=sum/n<3&&max<10}if(dark&&begin<0)begin=y;if(!dark&&begin>=0){if(y-begin>=4)regions.push({flag:'low_intensity_band',assessment:'Review dark coverage; physical cause unknown',evidence:'Near-black rows in the decoded image. This may be a margin or low return, not a confirmed motion dropout.',box_xyxy_pixels:[0,begin,image.width,y]});begin=-1}}return{regions,coverage:{unassessed:[],scope:'Image-only dark-band observations; no motion/altitude inference'},method:'near-black row screening; original acoustic shadows preserved'}}
async function process(j:Obj){const begun=performance.now();try{
 if(j.request.models[0]!=='sss-pipeline-v3'){await processSpecialist(j);return}
 j.state='processing';j.progress={stage:'loading_model',elapsed_seconds:0};j.message='Preparing verified ONNX model (first use downloads 10.6 MB from Hugging Face).';await save(j);
 const {ort,model}=await loadModel(),s=await get('sources',j.request.source_id);const im=await createImageBitmap(s.image);const source=canvas(im.width,im.height);source.getContext('2d')!.drawImage(im,0,0);im.close();const tile=canvas(640,640),ctx=tile.getContext('2d',{willReadFrequently:true})!,boxes:Obj[]=[];const windows=starts(source.height).flatMap(y=>starts(source.width).map(x=>[x,y]));
 if(windows.length>48)throw Error('Too many image tiles for the browser. Use a smaller image or the local app.');
 for(let k=0;k<windows.length;k++){
  if(j.cancellation_requested)throw Error('CANCELLED');const[x,y]=windows[k],w=Math.min(640,source.width-x),h=Math.min(640,source.height-y);ctx.fillStyle='rgb(114,114,114)';ctx.fillRect(0,0,640,640);ctx.drawImage(source,x,y,w,h,0,0,w,h);const pixels=ctx.getImageData(0,0,640,640).data,input=new Float32Array(3*640*640);for(let i=0;i<640*640;i++){input[i]=pixels[i*4]/255;input[i+640*640]=pixels[i*4+1]/255;input[i+2*640*640]=pixels[i*4+2]/255}
  const tensor=new ort.Tensor('float32',input,[1,3,640,640]),output=await model.run({[model.inputNames[0]]:tensor});const out:any=output[model.outputNames[0]],raw=out.data as Float32Array; if(out.dims.length!==3||out.dims[1]!==5)throw Error('Unexpected detector output shape');const n=out.dims[2],candidates:Obj[]=[];
  for(let i=0;i<n;i++){const score=raw[4*n+i];if(!Number.isFinite(score))throw Error('Nonfinite model output');if(score>.001){const cx=raw[i],cy=raw[n+i],bw=raw[2*n+i],bh=raw[3*n+i];candidates.push({score,box:[cx-bw/2,cy-bh/2,cx+bw/2,cy+bh/2]})}}
  for(const b of nms(candidates,.7,100)){const[a,c,d,e]=b.box;const box=[Math.max(x,a+x),Math.max(y,c+y),Math.min(x+w,d+x),Math.min(y+h,e+y)];if(box[2]>box[0]&&box[3]>box[1])boxes.push({...b,box})}
  tensor.dispose();for(const v of Object.values(output) as any[])v.dispose();j.progress={stage:'predicting',current:k+1,total:windows.length,elapsed_seconds:+((performance.now()-begun)/1000).toFixed(2)};j.message=`Analyzing tile ${k+1} of ${windows.length}`;await save(j);await new Promise(r=>setTimeout(r,0));
 }
 if(j.cancellation_requested)throw Error('CANCELLED');const detected=nms(boxes,.5).filter(b=>b.score>=THRESHOLD);j.contexts={};const detections=[];
 for(let i=0;i<detected.length;i++){const b=detected[i],id=uid(),[x,y,z,t]=b.box;const context=canvas(Math.max(1,Math.ceil(z-x)),Math.max(1,Math.ceil(t-y)));context.getContext('2d')!.drawImage(source,x,y,z-x,t-y,0,0,context.width,context.height);j.contexts['contexts/'+id+'.png']=await blob(context);detections.push({candidate_id:id,candidate_type:'model_detection',class_name:'Pipeline',class_id:0,original_class:'Pipeline',modality:'SSS_LF',model_id:'sss-pipeline-v3',model_version:'bluecho-sss-lf-pipeline-0.1.0',model_sha256:HASH,source_sha256:s.sha,model_score:b.score*100,raw_score:b.score,score_type:'uncalibrated_model_score_0_100',box_xyxy_pixels:b.box,pixel_dimensions:{width:z-x,height:t-y},...location(b.box,s.metadata),review_state:'unreviewed',review_history:[],evidence:{context:'contexts/'+id+'.png'},quality_flags:[]})}
 const q=quality(source);const qualityCanvas=canvas(source.width,source.height),qc=qualityCanvas.getContext('2d')!;qc.drawImage(source,0,0);qc.fillStyle='#f5b54b44';for(const r of q.regions){const b=r.box_xyxy_pixels;qc.fillRect(b[0],b[1],b[2]-b[0],b[3]-b[1])}j.qualityImage=await blob(qualityCanvas);
 j.result={schema_version:'bluecho-browser/1.0',runtime:'onnxruntime-web 1.30.0 WASM CPU',image_dimensions:{width:source.width,height:source.height},source_sha256:s.sha,source_reference:{file:s.filename,channel:null,ping_start:null,ping_end:null},modality:'SSS_LF',detections,unvalidated_proposals:[],quality:q,tracks:{features:[]},map_layers:{processed:[]},positioning_metadata:s.metadata||null,review_revision:0,review_records:[],rescan_requests:[],saved_example:false,threshold:THRESHOLD,preprocessing:{tile_size:640,stride:480,padding:114},merging:{tile_iou:.7,source_iou:.5,reconstructs_segments:false},evidence_scope:'Correlated single-survey development model. Browser execution is a separately checked runtime, not a new field benchmark.'};j.windows=[{id:'0',label:'Full image',reference:{ping_start:null,ping_end:null}}];j.state='completed_with_warnings';j.message='Analysis complete. Review candidates and export your report.';j.progress.stage='complete';j.runtime={elapsed_seconds:(performance.now()-begun)/1000,tile_count:windows.length,device:'Browser WASM CPU'};await save(j);await hydrate(j);
 }catch(e){j.state=j.cancellation_requested?'cancelled':'failed';j.message=j.cancellation_requested?'Inspection cancelled. Start a new inspection to retry.':(e as Error).message;await save(j)}
}
async function processSpecialist(j:Obj){
 const begun=performance.now(),spec=SPECIALISTS.find(m=>m.id===j.request.models[0])!;
 j.state='processing';j.progress={stage:'loading_model',current:0,total:1};j.message=`Loading ${spec.name}; first use downloads ${(spec.bytes/1e6).toFixed(1)} MB.`;await save(j);
 const {ort,model}=await loadModel(spec.hash,spec.url);if(j.cancellation_requested)throw Error('CANCELLED');const s=await get('sources',j.request.source_id);const bitmap=await createImageBitmap(s.image);const source=canvas(bitmap.width,bitmap.height);source.getContext('2d')!.drawImage(bitmap,0,0);bitmap.close();
 if(Math.max(source.width/source.height,source.height/source.width)>4)throw Error('This specialist expects cropped sonar frames with aspect ratio at most 4:1. Crop long strips into overlapping windows; use the pipeline route for full pipeline strips.');
 j.progress.stage='predicting';j.message=`Running ${spec.name} on this device`;await save(j);
 const prediction=await predictSpecialist(ort,model,source,spec);if(j.cancellation_requested)throw Error('CANCELLED');j.contexts={};const candidates=[];
 for(const b of prediction.boxes){const id=uid(),[x,y,z,t]=b.box,c=canvas(Math.max(1,Math.ceil(z-x)),Math.max(1,Math.ceil(t-y)));c.getContext('2d')!.drawImage(source,x,y,z-x,t-y,0,0,c.width,c.height);j.contexts['contexts/'+id+'.png']=await blob(c);candidates.push({candidate_id:id,candidate_type:spec.unvalidated.includes(b.classId)?'unvalidated_proposal':'model_detection',class_name:spec.classes[b.classId],class_id:b.classId,original_class:spec.classes[b.classId],modality:spec.modality,model_id:spec.id,model_version:spec.hash.slice(0,12),model_sha256:spec.hash,source_sha256:s.sha,model_score:b.score*100,raw_score:b.score,score_type:'uncalibrated_model_score_0_100',box_xyxy_pixels:b.box,pixel_dimensions:{width:z-x,height:t-y},...location(b.box,s.metadata),review_state:'unreviewed',review_history:[],evidence:{context:'contexts/'+id+'.png'},quality_flags:[],evidence_status:spec.evidence,provenance:{source:spec.source,terms:spec.license}})}
 const q=quality(source);const qualityCanvas=canvas(source.width,source.height),qc=qualityCanvas.getContext('2d')!;qc.drawImage(source,0,0);qc.fillStyle='#f5b54b44';for(const region of q.regions){const [x,y,z,t]=region.box_xyxy_pixels;qc.fillRect(x,y,z-x,t-y)}j.qualityImage=await blob(qualityCanvas);j.result={schema_version:'bluecho-browser/1.0',runtime:'onnxruntime-web 1.30.0 WASM CPU',image_dimensions:{width:source.width,height:source.height},source_sha256:s.sha,source_reference:{file:s.filename,channel:null,ping_start:null,ping_end:null},modality:spec.modality,detections:candidates.filter(d=>d.candidate_type==='model_detection'),unvalidated_proposals:candidates.filter(d=>d.candidate_type==='unvalidated_proposal'),quality:q,tracks:{features:[]},map_layers:{processed:[]},positioning_metadata:s.metadata||null,review_revision:0,review_records:[],rescan_requests:[],saved_example:false,threshold:spec.threshold,preprocessing:prediction.preprocessing,merging:prediction.merging,evidence_scope:spec.evidence,models:[{id:spec.id,sha256:spec.hash,source:spec.source,terms:spec.license,classes:spec.classes}]};j.windows=[{id:'0',label:'Full image',reference:{ping_start:null,ping_end:null}}];j.state='completed_with_warnings';j.message='Specialist analysis complete. Review class identity and source compatibility.';j.progress={stage:'complete',current:1,total:1,elapsed_seconds:+((performance.now()-begun)/1000).toFixed(2)};j.runtime={elapsed_seconds:(performance.now()-begun)/1000,tile_count:1,device:'Browser WASM CPU'};await save(j);await hydrate(j);
}
async function pump(){if(working)return;working=true;try{let next;while(next=[...jobs.values()].find(j=>j.state==='queued'))await process(next)}finally{working=false}}
let initialized=false;
async function init(){if(initialized)return;for(const j of await list('jobs')){if(j.demo?.kind==='synthetic_ui_demo')continue;if(['queued','processing'].includes(j.state)){j.state='failed';j.message='Browser closed during processing. Start a new inspection to retry.';await put('jobs',j.id,j)}jobs.set(j.id,j)}initialized=true}
async function createDemo(request:Obj={}){
 const existing=[...jobs.values()].filter(j=>j.demo);if(existing.length>=12)throw Error('Demo history is full. Clear demo history from Reports to explore more samples.');
 const scenario=request.scenario||nextDemoScenario(request.exclude||existing.sort((a,b)=>b.created.localeCompare(a.created))[0]?.demo.scenario);
 const sample=REAL_DEMO_SAMPLES.find(s=>s.id===scenario);if(!sample)throw Error('Choose an available real sonar sample');
 async function asset(name:string){const expected=(sample!.files as Record<string,string|undefined>)[name];if(!expected)throw Error('Sample asset is not listed in its manifest');const r=await fetch('/real-demo/'+scenario+'/'+name);if(!r.ok)throw Error('Could not load real sonar sample. Check your connection and retry.');const bytes=await r.arrayBuffer();if(await sha(bytes)!==expected)throw Error('Real sample checksum mismatch');return new Blob([bytes],{type:name.endsWith('.png')?'image/png':'application/json'})}
 const result=JSON.parse(await(await asset('results.json')).text());if(result.demo?.kind!=='real_sonar_saved_inference'||result.demo.synthetic!==false)throw Error('Sample must contain genuine sonar and saved inference provenance');
 const image=await asset('original.png'),qualityImage=await asset('quality.png'),contexts:Obj={};
 await Promise.all([...result.detections,...result.unvalidated_proposals].map(async(d:Obj)=>{contexts[d.evidence.context]=await asset(d.evidence.context)}));
 const attributionResponse=await fetch('/real-demo/ATTRIBUTION.md');if(!attributionResponse.ok)throw Error('Could not load source attribution');const sourceAttribution=await attributionResponse.text();
 const sourceId='demo_source_'+uid(),jobId='demo_'+uid(),filename=sample.name+' · '+result.demo.source_filename;
 const source={id:sourceId,filename,sha:result.source_sha256,image,demo:true,metadata:result.positioning_metadata,metadata_available:!!result.positioning_metadata,info:{...result.image_dimensions,bytes:image.size,format:'image',modality:sample.modality,sha256:result.source_sha256}};
 const job={id:jobId,filename,sourceAttribution,request:{source_id:sourceId,models:[sample.model],modality:sample.modality},demo:result.demo,state:'completed_with_warnings',message:result.demo.inference,created:new Date().toISOString(),revision:0,windows:[{id:'0',label:sample.name,reference:{ping_start:null,ping_end:null}}],saved_example:true,progress:{stage:'saved_real_inference'},result,contexts,qualityImage,runtime:{device:'Saved local CPU inference',inference_performed_on_open:false,original_timings:result.timings}};
 await put('sources',sourceId,source);await save(job);await hydrate(job);return publicJob(job);
}
async function clearDemos(){const d=await db();for(const j of [...jobs.values()].filter(j=>j.demo)){await new Promise<void>((resolve,reject)=>{const tx=d.transaction(['sources','jobs'],'readwrite');tx.objectStore('sources').delete(j.request.source_id);tx.objectStore('jobs').delete(j.id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});jobs.delete(j.id);for(const[key,value]of urls)if(key.includes('/jobs/'+j.id+'/')){URL.revokeObjectURL(value);urls.delete(key)}}return{ok:true}}
export async function browserCall(path:string,body?:any):Promise<any>{await init();
 if(path==='/demo')return createDemo(body);
 if(path==='/demo/clear')return clearDemos();
 if(path==='/capabilities')return{version:'0.6.2',deployment:'browser',worker_limit:1,max_upload_mib:32,models:[{id:'sss-pipeline-v3',modalities:['SSS_LF'],classes:{0:'Pipeline'},state:'ready',evidence:'Pipeline only. Frozen single-survey development model; browser CPU inference.',hash:HASH},...SPECIALISTS.map(m=>({id:m.id,name:m.name,modalities:[m.modality],classes:Object.fromEntries(m.classes.map((c,i)=>[i,c])),state:'ready',evidence:m.evidence,hash:m.hash,source:m.source,license:m.license,download_mb:+(m.bytes/1e6).toFixed(1)}))],unavailable:['Entangled nets: no validated real-sonar detector installed','Material identification: unsupported','Additional classes are sensor-specific; inspect model evidence before use']};
 if(path==='/examples')return[];
 if(path==='/sources'){
  const file=body.get('file') as File;if((await list('sources')).filter(s=>!s.demo).length>=20)throw Error('Browser source limit reached. Download reports, then clear site data to start a fresh workspace.');const decoded=await decode(file),s={id:uid(),filename:file.name,sha:await sha(await file.arrayBuffer()),info:{width:decoded.width,height:decoded.height,bytes:file.size,format:'image',modality:'SSS_LF'},image:decoded.image,metadata_available:false};Object.assign(s.info,{sha256:s.sha});await put('sources',s.id,s);const{image,...pub}=s;return pub;
 }
 const parts=path.split('/').filter(Boolean);
 if(parts[0]==='sources'&&parts[2]==='metadata'){const s=await get('sources',parts[1]);if(!s)throw Error('Source not found');const file=body.get('file') as File;if(file.size>1024*1024)throw Error('Browser metadata is limited to 1 MiB');const m=JSON.parse(await file.text());validateMetadata(m,s);s.metadata=m;s.metadata_available=true;await put('sources',s.id,s);const{image,...pub}=s;return pub}
 if(path==='/jobs'&&body){const s=await get('sources',body.source_id);const compatible=body.models?.length===1&&((body.models[0]==='sss-pipeline-v3'&&body.modality==='SSS_LF')||SPECIALISTS.some(m=>m.id===body.models[0]&&m.modality===body.modality));if(!s||!compatible)throw Error('Select one compatible model and its source modality');if(s.metadata&&s.metadata.modality!==body.modality)throw Error('Attached metadata modality does not match the selected model');if([...jobs.values()].filter(j=>['queued','processing'].includes(j.state)).length>=4)throw Error('Queue is full. Wait for an inspection to finish.');const j={id:uid(),filename:s.filename,request:clone(body),state:'queued',message:'Waiting for browser inference',created:new Date().toISOString(),revision:0,windows:[],saved_example:false,progress:{stage:'queued'}};await save(j);setTimeout(()=>pump(),0);return publicJob(j)}
 if(path==='/jobs')return[...jobs.values()].sort((a,b)=>b.created.localeCompare(a.created)).map(publicJob);
 if(parts[0]==='jobs'){
  const j=jobs.get(parts[1]);if(!j)throw Error('Inspection not found in this browser');
  if(parts.length===2)return publicJob(j);
  if(parts[2]==='cancel'){j.cancellation_requested=true;if(j.state==='queued'){j.state='cancelled';j.message='Cancelled before processing'}await save(j);return publicJob(j)}
  if(!j.result)throw Error('Results are not ready');const r=j.result;
  if(parts[2]==='windows'&&parts[3]==='0'){
   if(parts.length===4){await hydrate(j);return clone(r)}
   if(parts[4]==='geotag'){
    if(r.demo)throw Error('This demo preserves its source metadata. Upload your own source to attach different metadata.');
    const s=await get('sources',j.request.source_id);const f=body.get('file') as File;const m=JSON.parse(await f.text());validateMetadata(m,s);if(m.modality!==j.request.modality)throw Error('Metadata modality must match the inspection');const updated=clone(j);updated.id=uid();updated.created=new Date().toISOString();updated.request.parent_job=j.id;updated.result.positioning_metadata=m;for(const d of [...updated.result.detections,...updated.result.unvalidated_proposals])Object.assign(d,location(d.box_xyxy_pixels,m));updated.message='Metadata applied; no new inference.';await save(updated);return publicJob(updated);
   }
   if(body?.revision!==r.review_revision)throw Error('Review changed. Refresh before saving.');
   if(parts[4]==='review'){
    const d=[...r.detections,...r.unvalidated_proposals].find((x:Obj)=>x.candidate_id===parts[5]);if(!d)throw Error('Candidate not found');const before=clone(d);if(!d.original_prediction){const original=clone(d);delete original.review_history;d.original_prediction=original}
    const states:Obj={retain:'retained',false_alert:'false_alert',uncertain:'uncertain',corrected:'corrected_by_reviewer'};if(body.action==='corrected'){const b=body.box;if(!Array.isArray(b)||b.length!==4||!b.every(Number.isFinite)||!(0<=b[0]&&b[0]<b[2]&&b[2]<=r.image_dimensions.width&&0<=b[1]&&b[1]<b[3]&&b[3]<=r.image_dimensions.height))throw Error('Box must lie within the original image');if(!body.label?.trim()||body.label.length>100)throw Error('Provide a label of 1–100 characters');d.class_name=body.label;d.box_xyxy_pixels=b;d.pixel_dimensions={width:b[2]-b[0],height:b[3]-b[1]};Object.assign(d,location(b,r.positioning_metadata))}if(states[body.action])d.review_state=states[body.action];const event={action:body.action,note:String(body.note||'').slice(0,2000),reviewer:body.reviewer||null,timestamp:new Date().toISOString(),revision:++r.review_revision,old:{label:before.class_name,box:before.box_xyxy_pixels},new:{label:d.class_name,box:d.box_xyxy_pixels}};d.review_history.push(event);r.review_records.push(event);j.revision=r.review_revision;await save(j);return{ok:true};
   }
   if(parts[4]==='rescan'){const b=body.region;if(!Array.isArray(b)||b.length!==4||!b.every(Number.isFinite)||!(0<=b[0]&&b[0]<b[2]&&b[2]<=r.image_dimensions.width&&0<=b[1]&&b[1]<b[3]&&b[3]<=r.image_dimensions.height)||!body.reason?.trim())throw Error('Provide an in-image region and a reason');r.rescan_requests.push({region:b,reason:body.reason,origin:'human_action',timestamp:new Date().toISOString()});j.revision=++r.review_revision;await save(j);return{ok:true}}
  }
 }
 throw Error('This operation requires the local BluEcho application.');
}
const escape=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function browserExport(base:string,format:string,scope:string,visible:string[]){const j=jobs.get(base.split('/')[2]);if(!j?.result)throw Error('No result to export');const r=clone(j.result);if(scope==='displayed'){r.detections=r.detections.filter((d:Obj)=>visible.includes(d.candidate_id));r.unvalidated_proposals=r.unvalidated_proposals.filter((d:Obj)=>visible.includes(d.candidate_id))}const allCandidates=[...r.detections,...r.unvalidated_proposals];r.export_scope=scope;const s=await get('sources',j.request.source_id);const json=JSON.stringify(r,null,2),geo=JSON.stringify({type:'FeatureCollection',features:allCandidates.map((d:Obj)=>({type:'Feature',geometry:d.coordinates?{type:'Point',coordinates:d.coordinates}:null,properties:{...d,review_revision:r.review_revision}}))},null,2);
 const fields=['candidate_id','demo','synthetic','candidate_type','evidence_status','class_name','model_score','latitude','longitude','x1','y1','x2','y2','pixel_width','pixel_height','review_state','model_version','model_sha256','source_sha256','review_revision'];const quote=(v:any)=>'"'+String(v??'').replaceAll('"','""')+'"';const csv=[fields.join(','),...allCandidates.map((d:Obj)=>[d.candidate_id,!!r.demo,false,d.candidate_type,d.evidence_status||r.evidence_scope,d.class_name,d.model_score,d.coordinates?.[1],d.coordinates?.[0],...d.box_xyxy_pixels,d.pixel_dimensions.width,d.pixel_dimensions.height,d.review_state,d.model_version,d.model_sha256,d.source_sha256,r.review_revision].map(quote).join(','))].join('\r\n');
 if(format==='json')return new Blob([json],{type:'application/json'});if(format==='csv')return new Blob([csv],{type:'text/csv'});if(format==='geojson')return new Blob([geo],{type:'application/geo+json'});
 const original=await createImageBitmap(s.image),c=canvas(original.width,original.height),ctx=c.getContext('2d')!;ctx.drawImage(original,0,0);original.close();ctx.strokeStyle='#0fd7ce';ctx.lineWidth=3;for(const d of allCandidates){const[x,y,z,t]=d.box_xyxy_pixels;ctx.strokeRect(x,y,z-x,t-y)}
 const zip=new JSZip();if(r.demo){zip.file('SOURCE-AND-LICENSE.json',JSON.stringify(r.demo,null,2));zip.file('ATTRIBUTION.md',j.sourceAttribution||JSON.stringify(r.demo,null,2));}zip.file('results.json',json);zip.file('detections.csv',csv);zip.file('detections.geojson',geo);zip.file('original.png',s.image);zip.file('annotated.png',await blob(c));zip.file('quality.png',j.qualityImage);zip.file('reviews.json',JSON.stringify(r.review_records,null,2));for(const[n,b]of Object.entries(j.contexts||{}))zip.file(n,b as Blob);zip.file('report.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>BluEcho anomaly report</title><style>body{font:15px system-ui;margin:40px;color:#183548}img{max-width:100%}table{border-collapse:collapse}td,th{padding:12px;border:1px solid #ddd;text-align:left}</style><h1>BluEcho · Anomaly report</h1><p>${escape(s.filename)} · Revision ${r.review_revision} · SIH 2026</p><p>${r.demo?'REAL SONAR DEMO: saved output from an actual detector run. Locations appear only from source metadata; identity and field accuracy are unverified.':'Uncalibrated scores. Coordinates are metadata estimates. Browser ONNX runtime.'}</p>${r.demo?`<p>${escape(r.demo.credit)} · ${escape(r.demo.license)} · ${escape(r.demo.source_url)} · <a href="ATTRIBUTION.md">Full attribution and data terms</a></p>`:''}<img src="annotated.png" alt="Sonar with detection boxes"><table><tr><th>Class</th><th>Evidence</th><th>Score</th><th>Latitude / longitude</th><th>Review</th></tr>${allCandidates.map((d:Obj)=>`<tr><td>${escape(d.class_name)}</td><td>${escape(d.candidate_type)}: ${escape(d.evidence_status||r.evidence_scope)}</td><td>${d.model_score.toFixed(1)}%</td><td>${escape(d.coordinates?[d.coordinates[1],d.coordinates[0]].join(', '):'Unavailable')}</td><td>${escape(d.review_state)}</td></tr>`).join('')}</table><p><a href="results.json">JSON</a> · <a href="detections.csv">CSV</a> · <a href="detections.geojson">GeoJSON</a></p><footer><p>Built for Smart India Hackathon 2026 by Khushi Mhamane, Sharon Melhi, Kirti Rajput, Peeyush Rampal, Aditya Banerjee, and Aditya SS Varma.</p></footer></html>`);return zip.generateAsync({type:'blob'});
}
