import React,{useState} from 'react';
import {Icon,modelName,modalityName,stateName} from './design';
type Obj=Record<string,any>;
export const reviewed=(d:Obj)=>!['unreviewed','pending',undefined,null].includes(d.review_state);

export function ReviewQueue({items,selected,choose}:{items:Obj[],selected:string,choose:(id:string)=>void}){
 const pending=items.filter(d=>!reviewed(d)),done=items.length-pending.length;
 return <section className="review-queue" aria-label="Human review queue"><div className="queue-heading"><div><span className="eyebrow">OPERATOR REVIEW</span><h2>{pending.length?`${pending.length} ${pending.length===1?'contact needs':'contacts need'} a decision`:items.length?'Every contact has a review decision':'No contacts to review'}</h2></div><span className="queue-count">{done}<small> / {items.length} reviewed</small></span></div><progress aria-label="Review completion" value={done} max={Math.max(1,items.length)}/><div className="contact-strip">{items.map((d,i)=><button key={d.candidate_id} className={selected===d.candidate_id?'active':''} onClick={()=>choose(d.candidate_id)} aria-label={`Review contact ${i+1}`}><span className={'contact-number '+(reviewed(d)?'done':'')}>{reviewed(d)?<Icon name="check" size={13}/>:String(i+1).padStart(2,'0')}</span><span><strong>{d.class_name}</strong><small>{String(d.review_state||'unreviewed').replaceAll('_',' ')}</small></span><b>{d.model_score.toFixed(1)}%</b></button>)}</div><p>Review decisions are operator judgments. They do not establish field truth or model accuracy.</p></section>
}

export function BatchInspection({caps,jobs,call,open}:{caps:Obj|null,jobs:Obj[],call:(path:string,body?:any)=>Promise<any>,open:(job:Obj)=>void}){
 const[files,setFiles]=useState<File[]>([]),[route,setRoute]=useState(''),[rows,setRows]=useState<Obj[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const routes=(caps?.models||[]).filter((m:Obj)=>m.state==='ready').flatMap((m:Obj)=>m.modalities.map((mod:string)=>({value:m.id+'|'+mod,label:modelName(m.id)+' / '+modalityName(mod)})));
 async function run(){setBusy(true);setError('');setRows([]);const [model,modality]=route.split('|');try{for(const file of files){try{const form=new FormData();form.append('file',file);const source=await call('/sources',form);const job=await call('/jobs',{source_id:source.id,models:[model],modality,channel:null,start_ping:0,max_pings:128,chunk_pings:16});setRows(r=>[...r,{name:file.name,id:job.id}])}catch(e){setRows(r=>[...r,{name:file.name,error:(e as Error).message}])}}}finally{setBusy(false)}}
 return <section className="panel batch-panel"><details><summary><span><Icon name="model"/>Batch image inspection <small>Up to 4 images · sequential inference</small></span></summary><p>Use images from the same sensor and frequency. Each source keeps its own result and review history. Add matching coordinates to individual results after processing.</p><div className="batch-controls"><label>Batch sonar images<input type="file" accept=".png,.jpg,.jpeg,.bmp,.pbm" multiple disabled={busy} onChange={e=>{const f=Array.from(e.target.files||[]);if(f.length>4){setError('Select at most 4 images per batch.');setFiles([])}else{setError('');setFiles(f)}}}/></label><label>Confirm batch model and modality<select value={route} onChange={e=>setRoute(e.target.value)} disabled={busy}><option value="">Select the matching sensor and model</option>{routes.map((r:Obj)=><option key={r.value} value={r.value}>{r.label}</option>)}</select></label><button className="primary" disabled={busy||!files.length||!route} onClick={run}>{busy?'Adding sources…':`Start batch${files.length?' ('+files.length+')':''}`}</button></div>{error&&<p role="alert">{error}</p>}<div aria-live="polite">{rows.map((r,i)=>{const job=jobs.find(j=>j.id===r.id);return <div className="batch-row" key={i}><strong>{r.name}</strong><span>{r.error||stateName(job?.state||'queued')}</span>{job&&<button onClick={()=>open(job)}>Open inspection</button>}</div>})}</div><p className="muted">Keep this page open while sources are added. Submitted jobs remain in Reports & history. One failed source does not discard successful inspections.</p></details></section>
}

export function reviewExport(result:Obj,job:Obj,items:Obj[]){
 return {schema_version:'bluecho-review-candidates/1.0',demo:result.demo||null,created_at:new Date().toISOString(),job_id:job.id,source_sha256:result.source_sha256,image_dimensions:result.image_dimensions,window_id:result.source_window||null,review_revision:result.review_revision,purpose:'Human-reviewed annotation candidates for further curation; NOT an automatically approved training dataset.',limitations:['Labels cover reviewed detector candidates only; missed objects are not exhaustively annotated.','False alerts are candidate-level judgments, not verified negative source images.','No automatic retraining. Preserve survey groups and test holdouts before reuse.'],candidates:items.filter(reviewed).map(d=>({candidate_id:d.candidate_id,demo:!!result.demo,class_name:d.class_name,box_xyxy_pixels:d.box_xyxy_pixels,review_state:d.review_state,model_id:d.model_id,model_sha256:d.model_sha256,original_prediction:d.original_prediction||{class_name:d.class_name,box_xyxy_pixels:d.box_xyxy_pixels,model_score:d.model_score},review_history:d.review_history||[]}))};
}
