export type SpecialistConfig={id:string;name:string;modality:string;classes:string[];size:number;threshold:number;url:string;hash:string;bytes:number;layout:'end2end'|'yolo';order:'RGB'|'BGR';evidence:string;source:string;license:string;unvalidated:number[]};
export const SPECIALISTS:SpecialistConfig[]=[
 {"id": "fls11-debris", "name": "FLS debris specialist", "modality": "FLS_ARIS", "classes": ["mine", "can", "bottle", "drink-carton", "chain", "propeller", "tire", "hook", "valve", "shampoo-bottle", "standing-bottle"], "size": 640, "threshold": 0.25, "url": "https://huggingface.co/SharonMelhi/BluEcho-FLS11-ONNX/resolve/0236bd3c550f0f2caf28a25a307e6ace13ec1b24/model.onnx", "hash": "385b4e1185e478ec7ae90fa3091586273ca956aa957cbba1dbb96eaeae351dc2", "bytes": 10583017, "layout": "yolo", "order": "RGB", "evidence": "Third-party 11-class forward-looking sonar model. Runtime checked on propeller, shampoo-bottle and can examples; independent accuracy not measured. Mine outputs are unvalidated proposals.", "source": "https://huggingface.co/SharonMelhi/BluEcho-FLS11-ONNX", "license": "Original Bhoumik Chandra Bagh MIT model; Ultralytics AGPL-3.0 and separate source-data terms; see model card.", "unvalidated": [0]},
 {id:'ghost-pot',name:'GhostVision crab pots',modality:'SSS',classes:['Crab-Pot'],size:640,threshold:.25,url:'https://huggingface.co/PINGEcosystem/gv-yolo26/resolve/818d51e9900efa3bd155dafb369145426fd6aa65/weights.onnx',hash:'0deec99405d2f85602e9947c90f46110dddb8d85669223c1ee35308f75cd318d',bytes:38167375,layout:'end2end',order:'RGB',evidence:'Experimental: fixed 32-image source-test sample found 4 of 39 labelled pots, with 3 false positives at score 0.25. Low recall; new-survey performance unmeasured.',source:'https://huggingface.co/PINGEcosystem/gv-yolo26',license:'CC BY-SA 4.0 model card; ONNX metadata also records Ultralytics AGPL-3.0.',unvalidated:[]},
 {id:'sonarvision-sss',name:'SonarVision wrecks & debris',modality:'SSS',classes:['unknown_debris','airplane','mine','wreck'],size:256,threshold:.25,url:'https://huggingface.co/Dinoman1221/sonarvision-yolov8-esi-v6/resolve/f83895e4ae398030dc6dcbb9e98fe71e950d6db7/yolo_esi_v6_fp32.onnx',hash:'33a620674479e6251a3fb487e2b6a47dca777e3d3dd51d49c77fec6b2043ba72',bytes:12241743,layout:'yolo',order:'BGR',evidence:'Experimental third-party labels. Unknown debris is a trained category, not universal anomaly detection. Mine identity is unverified; mine-labelled outputs remain proposals.',source:'https://huggingface.co/Dinoman1221/sonarvision-yolov8-esi-v6',license:'Author MIT model card; ONNX metadata records Ultralytics AGPL-3.0.',unvalidated:[2]},
];
type Box={box:number[];score:number;classId:number};
const overlap=(a:number[],b:number[])=>{const intersection=Math.max(0,Math.min(a[2],b[2])-Math.max(a[0],b[0]))*Math.max(0,Math.min(a[3],b[3])-Math.max(a[1],b[1]));return intersection/Math.max(1e-12,(a[2]-a[0])*(a[3]-a[1])+(b[2]-b[0])*(b[3]-b[1])-intersection)};
export async function predictSpecialist(ort:any,model:any,source:HTMLCanvasElement,spec:SpecialistConfig){
 const size=spec.size,ratio=Math.min(size/source.width,size/source.height),w=Math.round(source.width*ratio),h=Math.round(source.height*ratio),left=Math.floor((size-w)/2),top=Math.floor((size-h)/2);
 const c=document.createElement('canvas');c.width=c.height=size;const ctx=c.getContext('2d')!;ctx.fillStyle='rgb(114,114,114)';ctx.fillRect(0,0,size,size);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='low';ctx.drawImage(source,0,0,source.width,source.height,left,top,w,h);
 const pixels=ctx.getImageData(0,0,size,size).data,data=new Float32Array(3*size*size),plane=size*size;
 for(let i=0;i<plane;i++){data[i]=pixels[i*4+(spec.order==='BGR'?2:0)]/255;data[plane+i]=pixels[i*4+1]/255;data[2*plane+i]=pixels[i*4+(spec.order==='BGR'?0:2)]/255}
 const input=new ort.Tensor('float32',data,[1,3,size,size]);let output:any;
 try{output=await model.run({[model.inputNames[0]]:input});const tensor=output[model.outputNames[0]],raw=tensor.data as Float32Array,dims=tensor.dims,boxes:Box[]=[];
  function add(b:number[],score:number,classId:number){if(!Number.isFinite(score)||!b.every(Number.isFinite))throw Error('Nonfinite specialist output');if(score<spec.threshold)return;if(!Number.isInteger(classId)||classId<0||classId>=spec.classes.length)throw Error('Unexpected specialist class ID');const box=[Math.max(0,(b[0]-left)/ratio),Math.max(0,(b[1]-top)/ratio),Math.min(source.width,(b[2]-left)/ratio),Math.min(source.height,(b[3]-top)/ratio)];if(box[2]>box[0]&&box[3]>box[1])boxes.push({box,score,classId})}
  if(spec.layout==='end2end'){if(dims.length!==3||dims[0]!==1||dims[2]!==6)throw Error('Unexpected end-to-end output shape');for(let i=0;i<dims[1];i++){const k=i*6;add(Array.from(raw.slice(k,k+4)),raw[k+4],raw[k+5])}}
  else{if(dims.length!==3||dims[0]!==1||dims[1]!==4+spec.classes.length)throw Error('Unexpected YOLO class/output shape');const n=dims[2];for(let i=0;i<n;i++){let cls=0,score=raw[4*n+i];for(let k=1;k<spec.classes.length;k++){if(raw[(4+k)*n+i]>score){score=raw[(4+k)*n+i];cls=k}}const x=raw[i],y=raw[n+i],w=raw[2*n+i],h=raw[3*n+i];add([x-w/2,y-h/2,x+w/2,y+h/2],score,cls)}}
  const kept:Box[]=[];for(const b of boxes.sort((a,b)=>b.score-a.score)){if(kept.every(k=>k.classId!==b.classId||overlap(k.box,b.box)<=.5))kept.push(b);if(kept.length===300)break}
  return {boxes:kept,preprocessing:{mode:'centered-letterbox',size,padding:114,color_order:spec.order,ratio,left,top,resized_width:w,resized_height:h,interpolation:'Browser Canvas bilinear; no stretching'},merging:{class_correct_nms_iou:.5,source_images:1}};
 }finally{input.dispose();if(output)for(const value of Object.values(output) as any[])value.dispose()}
}
