import React,{useState} from 'react';
import {Icon,modelName,modalityName,stateName} from './design';
type Obj=Record<string,any>;

export function ReportsPage({jobs,open,demo,clearDemos,batch}:{jobs:Obj[],open:(j:Obj)=>void,demo:()=>void,clearDemos:()=>void,batch:React.ReactNode}){
 const[query,setQuery]=useState(''),[filter,setFilter]=useState('all');
 const visible=jobs.filter(j=>j.filename.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='demo'&&j.demo||filter==='uploads'&&!j.demo||filter==='attention'&&['failed','cancelled'].includes(j.state)));
 return <div className="reports-page"><div className="workspace-page-heading"><div><p className="section-kicker">YOUR INSPECTION LIBRARY</p><h1>Reports & history</h1><p>Return to a finding. Continue a review. Take the evidence with you.</p></div><button onClick={demo}><Icon name="scan" size={17}/>Explore a demo</button></div>
  <section className="report-library panel"><div className="library-controls"><label><Icon name="file" size={17}/><input aria-label="Search inspections" type="search" placeholder="Find an inspection…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter inspections" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All inspections</option><option value="uploads">My uploads</option><option value="demo">Demo scenes</option><option value="attention">Needs attention</option></select></div>
  {visible.length?<div className="inspection-list">{visible.map(j=><button className="inspection-row" key={j.id} onClick={()=>open(j)}><span className={'report-symbol '+(j.demo?'is-demo':'')}><Icon name={j.demo?'wave':'file'} size={23}/></span><span className="report-name"><strong>{j.filename.replace(/^DEMO - /,'')}</strong><small>{j.demo?'Generated demo scene':j.saved_example?'Saved source example':'Your inspection'} · {new Date(j.created).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</small></span><span className={'badge '+(j.demo?'demo-label':'')}>{j.demo?'Demo':stateName(j.state)}</span><span className="report-open">Open report <Icon name="arrow" size={16}/></span></button>)}</div>:<div className="workspace-empty"><Icon name="file" size={34}/><h2>{jobs.length?'No matching inspections':'Your findings belong here'}</h2><p>{jobs.length?'Try a different search or filter.':'Run an inspection or explore a demo to start your library.'}</p>{!jobs.length&&<button className="primary" onClick={demo}>Try demo<Icon name="arrow" size={16}/></button>}</div>}
  <div className="library-footer"><p>Export reports to keep a copy outside this workspace.</p>{jobs.some(j=>j.demo)&&<button onClick={clearDemos}>Clear demo history</button>}</div></section>{batch}
 </div>;
}

export function ModelsPage({caps,choose}:{caps:Obj|null,choose:(m:Obj)=>void}){
 const[sensor,setSensor]=useState('all');const models=(caps?.models||[]).filter((m:Obj)=>sensor==='all'||m.modalities.some((x:string)=>x.startsWith(sensor)));
 return <div className="models-page"><div className="workspace-page-heading"><div><p className="section-kicker">CHOOSE WITH CONTEXT</p><h1>Models & system</h1><p>The right specialist starts with the sonar that produced your image.</p></div><span className="engine-status"><i/>{caps?'Workspace connected':'Connecting'}</span></div>
  <div className="model-guidance"><Icon name="wave" size={25}/><p>Match the sensor, then read the model’s scope. A model being available does not establish accuracy on your survey.</p></div>
  <section aria-label="Model availability"><div className="model-library-heading"><h2>Model availability</h2><div className="sensor-filters">{[['all','All sensors'],['SSS','Side-scan'],['FLS','Forward-looking']].map(([id,label])=><button key={id} aria-pressed={sensor===id} className={sensor===id?'active':''} onClick={()=>setSensor(id)}>{label}</button>)}</div></div>
  <div className="model-library">{models.map((m:Obj)=><article className="model-profile" key={m.id}><div className="model-profile-head"><span className="model-symbol"><Icon name={m.modalities.some((x:string)=>x.startsWith('FLS'))?'wave':'scan'} size={25}/></span><span className={'badge '+(m.state==='ready'?'available':'')}>{m.state==='ready'?'Available':'Unavailable'}</span></div><p className="model-sensor">{m.modalities.map(modalityName).join(' / ')}</p><h3>{modelName(m.id)}</h3><p className="model-scope">{m.evidence}</p><details><summary>Classes & model details</summary><div className="model-class-list">{Object.values(m.classes||{}).map((c:any)=><span key={c}>{c}</span>)}</div><pre>{JSON.stringify(m,null,2)}</pre></details><div className="model-profile-footer">{m.source?<a href={m.source} target="_blank" rel="noreferrer">Source & licence ↗</a>:<span>Source details in model record</span>}<button disabled={m.state!=='ready'} onClick={()=>choose(m)}>Use model<Icon name="arrow" size={15}/></button></div></article>)}</div></section>
  <details className="model-limits"><summary>Coverage, limitations & system details</summary>{caps?.unavailable.map((x:string)=><p key={x}>{x}</p>)}<p>Detection scores are uncalibrated. Class names do not establish material identity or field truth.</p><pre>{JSON.stringify(caps,null,2)}</pre></details>
 </div>;
}

export function DemoGuide({scenario,change,exit,busy}:{scenario:string,change:(s?:string)=>void,exit:()=>void,busy:boolean}){
 return <section className="demo-guide"><div className="demo-guide-title"><span className="demo-label">DEMO WORKSPACE</span><h2>Take the controls.</h2><p>Select a contact, try a review decision, explore the map, or download a report.</p><small>Generated sonar, simulated contacts, scores and locations. No AI inference or real survey data.</small></div><div className="demo-guide-actions"><label>Demo scene<select aria-label="Demo scene" value={scenario} disabled={busy} onChange={e=>change(e.target.value)}><option value="pipeline">Pipeline corridor</option><option value="objects">Scattered returns</option><option value="coverage">Interrupted coverage</option></select></label><div><button disabled={busy} onClick={()=>change(scenario)}><Icon name="wave" size={16}/>Shuffle scene</button><button onClick={exit}>Exit demo</button></div></div></section>;
}
